cc_library(
  name = "algos",
  srcs = ["movingAverage.cpp"],
  hdrs = [
    "IAlgorithm.hpp",
    "movingAverage.hpp",
  ],
  visibility = ["//src:__pkg__"],
  deps = [
    "//src/dataRetrievers:retrievers",
    "//src/tradeManagers:managers",
  ],
)
